spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  spring:
    redis:
      host: localhost
      port: 6379
      password: rootpassword



server:
  port: 8080

redis:
  ttl: 300

